import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginButton from "./LoginButton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutButton from "./LogoutButton";
import { cookies } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "코딩애플-Next.js",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);  // 현재 로그인된 유저이름, 이메일 등이 남음

  // 쿠키 값을 비동기적으로 가져오기
  let cookieValue = await cookies().get('name');
  console.log(cookieValue);  // 쿠키값 출력

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {/* JSX 안에서 if문을 쓰고싶으면 삼항연산자 사용 */
            session ? <div>{session.user.name} <LogoutButton/></div> : <LoginButton />
          }
        </div>
        {children}
      </body>
    </html>
  );
}
