import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginButton from "./LoginButton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutButton from "./LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "코딩애플-Next.js",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);  // 현재 로그인된 유저이름, 이메일 등이 남음
  // console.log(session);

  /** console 결과
   * {
        user: {
          name: 'Nova',
          email: 'heetask@gmail.com',
          image: 'https://avatars.githubusercontent.com/u/56466589?v=4'
        }
      }
   */

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {/* JSX 안에서 if문을 쓰고싶으면 삼항연산자 사용 */
            session ? <div>{session.user.name} <LogoutButton/></div> : <LoginButton />
          }
        </div>
        {children}
      </body>
    </html>
  );
}
